config/routes.rb
Rails.application.routes.draw do


  root to: "pages#home"

  get 'about', to: 'pages#about'

  resources :posts, only: [:show]

  comfy_route :cms_admin, :path => '/admin'
  # Make sure this routeset is defined last
  comfy_route :cms, :path => '/', :sitemap => false

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Post.all
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Open+Sans' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="page--purple">
  <h1>About Page</h1>
  <p>This is a test blog</p>
</div>

app/views/pages/home.html.erb
<div class="page--yellow">
  <div class="row">
    <% @posts.each do |post| %>
      <div class="col-xs-4 col-xs-push-4">
        <%= link_to post.title, post_path(post) %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>
<p><%= @post.published %></p>

app/views/shared/_navbar.html.erb
<%= link_to "Home", root_path %>
<%= link_to "About", about_path %>